import Head from 'next/head'
import React, { useState } from 'react';
import Navbar from '../components/Navbar'
import Hero from '../components/Hero'
import Schedule from '../components/Schedule'
import About from '../components/About'
import CurrentTeams from '../components/CurrentTeams'
import PastWinners from '../components/PastWinners'
import CustomCursor from '../components/CustomCursor'

export default function Home() {

  const [showing, setShowing] = useState(0);

  const handleSetShowing = (index) => {
    setShowing(index)
  }

  const navItems = [
    {
        id: 0,
        name: "Schedule"
    },
    {
        id: 1,
        name: "About"
    },
    {
        id: 2,
        name: "Current Teams"
    },
    {
        id: 3,
        name: "Past Winners"
    },
]

  return (
    <div className="home">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CustomCursor />
      <Navbar navItems={navItems} showing={showing} handleSetShowing={handleSetShowing}/>
      <Hero/>
        {showing === 0 && <Schedule/> }
        {showing === 1 && <About/> }
        {showing === 2 && <CurrentTeams/> }
        {showing === 3 && <PastWinners/> }
 

      <div class="flier"><img src="softball.png" width="200"/></div>
      <div class="bat"><img src="bat.png" width="300"/></div>
    </div>
  )
}
