import Head from 'next/head'
import React, { useState, useEffect } from 'react';
import Navbar from '../components/Navbar'
import Hero from '../components/Hero'
import Schedule from '../components/Schedule'
import About from '../components/About'
import WeeklyResults from '../components/WeeklyResults'
import CurrentTeams from '../components/CurrentTeams'
import Standings from '../components/Standings'
import CustomCursor from '../components/CustomCursor'
import AnimatedCursor from "react-animated-cursor"

export default function Home({props}) {

  const [showing, setShowing] = useState(0);

  const handleSetShowing = (index) => {
    setShowing(index)
  }

  const navItems = [
    {
        id: 0,
        name: "About",
    },
    {
        id: 1,
        name: "Schedule",
    },
    {
        id: 2,
        name: "Weekly Results",
    },
    {
      id: 3,
      name: "Standings",
  },
]



  return (
    <div className="home">
      <Head>
        <title>North Portland Softball League</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Courier+Prime&family=Staatliches&display=swap" rel="stylesheet" />
      </Head>

      <Navbar navItems={navItems} showing={showing} handleSetShowing={handleSetShowing} props={props}/>
      <Hero/>
        {showing === 0 && <About props={props}/> }
        {showing === 1 && <Schedule props={props}/> }
        {showing === 2 && <WeeklyResults props={props}/> }
        {showing === 3 && <Standings props={props}/> }

      <div className="flier"><img src="softball.png" width="200"/></div>
      <div className="bat"><img src="bat.png" width="300"/></div>
    </div>
  )
}



export async function getServerSideProps() {

  const res = await fetch(`http://localhost:8888/north-portland-softball-league-backend/wp-json/wp/v2/pages`);
  
  let props = await res.json();

  return {
    props: {
      props
    },
  };
}
